# frozen_string_literal: true

source 'http://rubygems.org'
gem 'aasm'
gem 'andand'
gem 'cloudinary', git: 'https://github.com/cloudinary/cloudinary_gem'
gem 'fastimage' # get image attributes, even from a url
gem 'nokogiri'
# gem "debase"
gem 'free-image' # image manipulation, at a basic level
gem 'mechanize'
# gem "mongo"
gem 'puma'
gem 'rails'
gem 'rerun', git: 'https://github.com/alexch/rerun'
# gem "rmagick"
gem 'roda', git: 'https://github.com/jeremyevans/roda' # alternative to sinatra; look into
gem 'ruby-debug-ide'
# gem "ruby-vips"
gem 'sequel' # database that has the same author as roda
# gem "shotgun"
gem 'rubocop'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'solargraph'
# gem "statemachine"
gem 'padrino'
gem 'ruby2d'
gem 'state_machine'
gem 'telegram_bot'
gem 'time_difference' # , git: "https://github.com/ZeroPivot/time_difference" # time difference algorithm (https://github.com/tmlee/time_difference)
gem 'twitter'
gem 'tzinfo'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw]
gem 'wdm' # For Windows Ruby Only
gem 'webrick'
gem 'yaml'
# gem "image_pro:wqcessing", git: "https://github.com/ZeroPivot/image_processing"
